spring.application.name=artistregistration
spring.datasource.url=jdbc:postgresql://localhost/artist_registration
spring.datasource.username=postgres
spring.datasource.password=Jo95123##
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update
